# Generated by Django 3.2.13 on 2022-06-29 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Categoria')),
                ('descripCategoria', models.CharField(max_length=100, verbose_name='Descrip Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('descripProducto', models.CharField(max_length=100, verbose_name='Descrip Producto')),
                ('glosaProducto', models.CharField(max_length=1000, verbose_name='Glosa Producto')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('imagen', models.ImageField(default=None, null=True, upload_to='productos', verbose_name='Imagen Producto')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
